stages:
  - build
  - deploy

deploy_review:
  stage: deploy
  image: garland/aws-cli-docker
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: https://staging.ejd.io/$CI_ENVIRONMENT_SLUG/
    on_stop: stop_review
  only:
  - branches
  except:
  - master
  script:
  - cp -r src/ public/
  - aws s3 sync public/ s3://staging.ejd.io/$CI_ENVIRONMENT_SLUG/ --delete --acl public-read

stop_review:
  stage: deploy
  image: garland/aws-cli-docker
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
  - branches
  except:
  - master
  when: manual
  script:
  - aws s3 rm --recursive s3://staging.ejd.io/$CI_ENVIRONMENT_SLUG

deploy_production:
  stage: deploy
  image: garland/aws-cli-docker
  environment: production
  only:
  - master
  script:
  - cp -r src/ public/
  - aws s3 sync public/ s3://ejd.io/ --delete --acl public-read
